version: '2.2'

services:
  php:
    image: php:5.6.40
    container_name: php
    environment:
      -  
    volumes:
      - 
    ports:
      - 8008:80
    networks:
      - app

  mysql:
    image: mysql:5.7
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3366:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: immo
    volumes:
      - ./data/mysql:/var/lib/mysql
    networks:
      - app

volumes:
  data:
    driver: local

networks:
  app:
    driver: bridge
